version: '3.0'

services:
  postgres-nestjs-db:
    image: postgres:16.1
    container_name: laravel-empresa
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - ./postgres:/var/lib/postgres/data
    ports:
      - ${DB_PORT}:${DB_PORT}
